[package]
name = "rust-biotools"
version = "0.1.0"
edition = "2021"
author = "Dean"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio = "*"
clap = { version = "3.2.22", features = ["derive"] }
